connect "BRC TMDS"
Click (Image:"TMDS ICON", WaitFor:60)
Click (Image: "Train Management System")
rightclick (Image:"BRC1000TrainSymbol", WaitFor:78)
Click (Image:"MOVETRAIN", WaitFor:16.7)
if imagefound(ImageName: "EMTImage") then
	Typetext controlKey,"w"
end if
Typetext controlkey, "w"
Put file resourcePath("BRC Window Names.csv") into WinNames
repeat with each line of WinNames
	click "Window"
	Log It
	Click (text: It, IgnoreSpaces:"Yes", Waitfor:15)
	
	repeat with each item of EveryImageLocation("EMTImage")
		Log it
		click It-(10,0)+(0,20)
		if imagefound(ImageName: "BRC1000TrainSymbol") then 
			RightClick (Image:"BRC1000TrainSymbol", WaitFor:78)
		Else
			rightclick it-(5,0)+(0,10)
		end if
		Click (Image:"EnterMainTrack", WaitFor:41)
		TypeText LeftArrow,RightArrow,ReturnKey
		Click (Image:"EMTYes", WaitFor:34)
		connect "BRC TMC"
		if imagefound (ImageName: "AUTHORITYReview", Waitfor:30) then
			Click (Image:"AUTHORITYReview", WaitFor:180)
			Click (Image:"AuthorityAcknowledge", WaitFor:34)
			Click (Image:"AuthorityReturn", WaitFor:28)
			wait 20
			connect "BRC TMDS"
			if imagefound(ImageName: "BRC1000TrainSymbol") then 
				RightClick (Image:"BRC1000TrainSymbol", WaitFor:78)
			Else
				rightclick it-(5,0)+(0,10)
			end if
			Click (Image:"CancelEMT", WaitFor:24)
			Click (Image:"EMTCancelYes", WaitFor:33)
			if imagefound(ImageName:"EMTActive") Then
				wait 15
				Click (Image: "TMDS ICON")
				click (image: "SYSTEMSUMMARY")
				Click (image: "AuthoritiesTab")
				click (image:"EMTOption")
				rightclick (image:"EMTOption")
				click (image:"CANCELENTERMAINTRACK")
				click (image:"CANCELENTERMAINTRACKAUTHORITY")
			end if
			Connect "BRC TMC"
			Click (Image:"AUTHORITYReview", WaitFor:180)
			Click (Image:"AuthorityVoidAcknowledge", WaitFor:28)
			Connect "BRC TMDS"
			if imagefound(ImageName: "BRC1000TrainSymbol") then 
				RightClick (Image:"BRC1000TrainSymbol", WaitFor:78)
			Else
				rightclick it-(5,0)+(0,10)
			end if
			Click (Image:"MOVETRAIN", WaitFor:16.7)
			
		Else if imageFound(ImageName: "SYNCHRONIZATIONERROR") then
			Click (Image:"SYNCHRONIZATIONERROR", waitfor:60)
			Click (image:"DegradedSystemAck", waitfor:60)
			Click (image: "Menu1", waitfor:60)
			click(image:"Cutout", waitfor:60)
			click(image: "CUTOUTENFORCEMENTYes", waitfor:60)
			Wait 20
			connect "BRC TMDS"
			if imagefound(ImageName: "BRC1000TrainSymbol") then 
				RightClick (Image:"BRC1000TrainSymbol", WaitFor:78)
			Else
				rightclick it-(5,0)+(0,10)
			end if
			Click (Image:"CancelEMT", WaitFor:24)
			Click (Image:"EMTCancelYes", WaitFor:33)
			wait 5
			if imagefound(ImageName:"EMTActive") Then
				wait 15
				Click (Image: "TMDS ICON", waitfor:60)
				click (image: "SYSTEMSUMMARY", waitfor:60)
				Click (image: "AuthoritiesTab", waitfor:60)
				click (image:"EMTOption", waitfor:60)
				rightclick (image:"EMTOption", waitfor:60)
				click (image:"CANCELENTERMAINTRACK", waitfor:60)
				click (image:"CANCELENTERMAINTRACKAUTHORITY", waitfor:60)
			end if
			Connect "BRC TMC"
			click(image: "menu1", waitfor:300)
			click(image:"CutIn", waitfor:300)
			click (Image: "ACTIVATEENFORCEMENTYes", waitfor:300)
			click (image: "AcceptConsist", waitfor:300)
			click (image: "SELECTCURRENTTRACK", waitfor:300)
			click (image: "SelectTrack Yes", waitfor:300)
			click (image: "North TTDirection", waitfor:300)
			click (image: "MainButton", waitfor:300)
			wait 45
			connect "BRC TMDS"
			if imagefound(ImageName: "BRC1000TrainSymbol") then 
				RightClick (Image:"BRC1000TrainSymbol", WaitFor:78)
			Else
				rightclick it-(5,0)+(0,10)
			end if
			Click (Image:"MOVETRAIN", WaitFor:16.7)
			
		end if
	End If


End Repeat
end repeat 
end repeat


