connect "SandSFRVBO"
Click (Image:"TMDS ICON", WaitFor:60)
Click "TrainManagement"

if imagefound(ImageName: "EMTImage") then
	Typetext controlKey,"w"
end if
Typetext controlkey, "w"
put file resourcePath("EMTSwitchReport.csv") into EMTSwitches
put item 9 of line 2 of EMTSwitches  into myOldScreen
put " " into myOldTracksUID
put 0 into mycount
repeat with each line of line 2 to -1 of EMTSwitches
	put item 2 of it into myTracksUID
	put item  9 of it into myCurScreen
	put item 6 of it into mySwitchPosition
	put item 7 of it into mySwitchLat
	put item 8 of it into mySwitchLong
	put (myswitchLat, mySwitchLong) into switchCoord
	if myCurScreen does not equal myOldScreen
		Click (Image:"Control", WaitFor:21)
		Click (Image:"RELEASETERRITORY", WaitFor:25)
		wait 5
		Click "CloseReleasePage"
		Click (Image:"Control", WaitFor:21)
		Click "SYSTEMLOGON"
		Click "TMDSUser"
		Typetext tabKey
		TypeText "1","1","1"
		Click "Ok_1"
		click (Text: myCurScreen, IgnoreSpaces:"Yes")
		TypeText InsertKey, altKey, InsertKey, InsertKey, InsertKey, InsertKey, InsertKey,InsertKey, InsertKey, InsertKey
		Click "LOAD"
		wait 30
		Click (Image: "TMDS ICON", waitfor:120)
		Click "TrainManagement"
		Typetext controlKey,"w"
		wait 10
	end if	
	log item 1 of it
	if myOldTracksUID = myTracksUID
		wait 5
		put mycount +1 into mycount
		rightclick myTrack
		click "POSITIONTRAIN"
		Click "EnterTrainSymbol"
		Click "SelectTrainSymbol"
		TypeText TabKey
		Click (Image:"PositionTrainSave", WaitFor:45)
		Click "TrainInUseYES"	
		rightclick (Image:"SFRVTrainSymbol")
		
		if imagefound(Imagename:"EnterMainTrack")
			Click (Image:"EnterMainTrack", WaitFor:41)
			Typetext Leftarrow, RightArrow
			if mycount > 0 then
				repeat mycount times
					Typetext downarrow
				end repeat
			end if
		Else
			Next REpeat
		end if
		
		
	Else
		put 0 into mycount
		wait 5
		if item 6 of it = "SPLB"
			
			put switchCoord + (27,90) into myTrack
			rightclick myTrack
			click "POSITIONTRAIN"
			Click "EnterTrainSymbol"
			Click "SelectTrainSymbol"
			TypeText TabKey
			Click (Image:"PositionTrainSave", WaitFor:45)
			Click "TrainInUseYES"	
			rightclick (Image:"SFRVTrainSymbol")
			
			Click (Image:"EnterMainTrack", WaitFor:41)
			Typetext Leftarrow, RightArrow
		end if
		
		If item 6 of it = "SPRT"
			
			put switchCoord + (25,90) into myTrack
			rightclick myTrack
			click "POSITIONTRAIN"
			Click "EnterTrainSymbol"
			Click "SelectTrainSymbol"
			TypeText TabKey
			Click (Image:"PositionTrainSave", WaitFor:45)
			Click "TrainInUseYES"	
			rightclick (Image:"SFRVTrainSymbol")
			
			Click (Image:"EnterMainTrack", WaitFor:41)
			Typetext Leftarrow, RightArrow
		End If
		
		If item 6 of it = "SPLT"
			
			put switchCoord + (10,90) into myTrack
			rightclick myTrack
			click "POSITIONTRAIN"
			Click "EnterTrainSymbol"
			Click "SelectTrainSymbol"
			TypeText TabKey
			Click (Image:"PositionTrainSave", WaitFor:45)
			Click "TrainInUseYES"	
			rightclick (Image:"SFRVTrainSymbol")
			
			Click (Image:"EnterMainTrack", WaitFor:41)
			Typetext Leftarrow, RightArrow
		End If
		
		If item 6 of it = "SPRB"
			
			put switchCoord + (30,90) into myTrack
			rightclick myTrack
			click "POSITIONTRAIN"
			Click "EnterTrainSymbol"
			Click "SelectTrainSymbol"
			TypeText TabKey
			Click (Image:"PositionTrainSave", WaitFor:45)
			Click "TrainInUseYES"	
			rightclick (Image:"SFRVTrainSymbol")
			
			Click (Image:"EnterMainTrack", WaitFor:41)
			Typetext Leftarrow, RightArrow
		End If
		
	End If
	
	
	
	Typetext ReturnKey
	TypeText LeftArrow,RightArrow,ReturnKey
	if imagefound(ImageName:"EMTForSFRV9999")
		Click (Image:"EMTForSFRV9999")
		TypeText DownArrow, ReturnKey
		Click (Image:"YES_1")
		
	Else
		Log "EMT Switch is here but cannto issue Authority"
		Next Repeat
	End If
	
	
	connect "SandSFRTATMC"
	if imagefound (ImageName: "AUTHORITYReview", Waitfor:30) then
		Click (Image:"AUTHORITYReview", WaitFor:180)
		Click (Image:"AuthorityAcknowledge", WaitFor:34)
		Click (Image:"AuthorityReturn", WaitFor:28)
		wait 20
		connect "SandSFRVBO"
		RightClick (Image:"SFRVTrainSymbol", WaitFor:78)
		
		Click (Image:"CancelEMT", WaitFor:24)
		Click (Image:"EMTCancelYes", WaitFor:33)
		
		Connect "SandSFRTATMC"
		Click (Image:"AUTHORITYReview", WaitFor:180)
		Click (Image:"AuthorityVoidAcknowledge", WaitFor:28)
		Connect "SandSFRVBO"	
		wait 15
		if imagefound(ImageName:"EMTActive") Then
			Click (Image: "TMDS ICON")
			click (image: "SYSTEMSUMMARY_1")
			Click (image: "AuthoritiesTab")
			click (image:"EMTOption")
			rightclick (image:"EMTOption")
			click (image:"CANCELENTERMAINTRACK")
			click (image:"CANCELENTERMAINTRACKAUTHORITY")
		end if
		
	Else
		
		if imageFound(ImageName: "SYNCHRONIZATIONERROR") then
			Click (Image:"SYNCHRONIZATIONERROR", waitfor:60)
			Click (image:"DegradedSystemAck", waitfor:60)
			Click (image: "Menu1", waitfor:60)
			click(image:"Cutout", waitfor:60)
			click(image: "CUTOUTENFORCEMENTYes", waitfor:60)
			Wait 20
			connect "SandSFRVBO"
			RightClick (Image:"SFRVTrainSymbol", WaitFor:78)
			
			Click (Image:"CancelEMT", WaitFor:24)
			Click (Image:"EMTCancelYes", WaitFor:33)
			wait 15
			if imagefound(ImageName:"EMTActive") Then
				Click (Image: "TMDS ICON", waitfor:60)
				click (image: "SYSTEMSUMMARY_1", waitfor:60)
				Click (image: "AuthoritiesTab", waitfor:60)
				click (image:"EMTOption", waitfor:60)
				rightclick (image:"EMTOption", waitfor:60)
				click (image:"CANCELENTERMAINTRACK", waitfor:60)
				click (image:"CANCELENTERMAINTRACKAUTHORITY", waitfor:60)
			end if
			Connect "SandSFRTATMC"
			click(image: "menu1", waitfor:300)
			click(image:"CutIn", waitfor:300)
			click (Image: "ACTIVATEENFORCEMENTYes", waitfor:300)
			click (image: "AcceptConsist", waitfor:300)
			click (image: "SELECTCURRENTTRACK", waitfor:300)
			click (image: "SelectTrack Yes", waitfor:300)
			click (image: "South", waitfor:300)
			click (image: "MainButton", waitfor:300)
			if imagefound (ImageName:"Active_1", waitfor:120)
				Connect "SandSFRVBO"
			Else 
				Wait 45
				connect "SandSFRVBO"
			end if	
		End if
	End If
	
	
	
	set myoldScreen to myCurScreen
	set myOldTracksUID to myTracksUID
End Repeat








