connect "SandSFRVBO"
Click (Image:"TMDS ICON", WaitFor:60)
Click "TrainManagement"

put the hour into myHour 
Log myhour
Put the minute into myMin
log mymin
Put the second into mySecs
log mysecs
log myhour, mymin, mysecs
log the international date && myhour & mymin &mysecs
put "C:/Users/Administrator/Documents/SFRTA T&T Sweeping Test" && the international date && myhour & mymin & mysecs & ".csv" into Myfile
open file myfile

Put file resourcePath("SFRV TNT LIMITS.csv") into Routes
Put line 1 of file resourcePath("TNTHeader.csv") && return into file myfile

put item 15 of line 2 of Routes into myOldScreen

repeat with each line of line 2 to -1 of Routes
	wait 5
	TypeText EscapeKey
	put item 15 of it into myCurScreen
	put item 1 of it into myUID
	put item 2 of it into myCP
	put item 11 of it into myStartLimit
	put item 12 of it into myEndLimit
	put item 14 of it into myTrkName
	put myCP && "From" && myStartLimit && "To" && myEndLimit && myTrkName into myLocation
	log myUID
	if myCurScreen does not equal myOldScreen
		Click (Image:"TMDS ICON", WaitFor:60)
		Click "TrainManagement"
		Click (Image:"Control", WaitFor:21)
		Click (Image:"RELEASETERRITORY", WaitFor:25)
		wait 5
		Click "CloseReleasePage"
		Click (Image:"Control", WaitFor:21)
		Click "SYSTEMLOGON"
		Click "TMDSUser"
		Typetext tabKey
		TypeText "1","1","1"
		Click "Ok_1"
		click (Text: myCurScreen)
		TypeText InsertKey, altKey, InsertKey, InsertKey, InsertKey, InsertKey, InsertKey,InsertKey, InsertKey, InsertKey
		Click "LOAD"
		wait 30
		Click (Image: "TMDS ICON", waitfor:120)
		Click "TrainManagement"
	end if
	
	log myCurScreen
	put myCurScreen into myOldScreen
	log myOldScreen
	put item 5 of it into myTrkLat
	put item 6 of it into myTrkLong
	
	put (myTrkLat,myTrkLong) into TrkCoord
	put TrkCoord + (30,90) into convertedTrackCoord
	
	Rightclick convertedTrackCoord
	if imagefound(ImageName:"T&TIssue")
		Click ("T&TIssue")
		click convertedTrackCoord
		wait 1
		rightclick ("BlackBackground")
		wait 2
		Typetext Tabkey, ReturnKey
		if imagefound (Imagename:"T&T TO TRAIN")
			Click "T&T TO Train"
			Click "SFRV9999"
			Click "TNTRead"
			Click "TNTRepeat"
			typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnkey, ReturnKey, ReturnKey, REturnKey, REturnkey
		Else 
			Rightclick convertedTrackCoord
			Click ("T&TIssue")
			click convertedTrackCoord
			wait 1
			rightclick ("BlackBackground")
			wait 2
			Typetext Tabkey, ReturnKey
			if imagefound (Imagename:"T&T TO TRAIN")
				Click "T&T TO Train"
				Click "SFRV9999"
				Click "TNTRead"
				Click "TNTRepeat"
				typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnkey, ReturnKey, ReturnKey, ReturnKEy, REturnKey
			Else 	
				Typetext EscapeKey
				put myUID into Item 1 of row
				put myLocation into item 2 of Row
				put "No Authority Created" into item 3 of Row
				Put "T&T Issue Option not available here" into item 4 of Row
				put "Not Acknowledged" into Item 5 of row
				put "No Kibana Information" into Item 6 of Row
				put CRLF & row after file myfile
				Next Repeat
			End If
		End If
	Else
		Typetext EscapeKey
		put myUID into Item 1 of row
		put myLocation into item 2 of Row
		put "No Authority Created" into item 3 of Row
		Put "T&T Issue Option not available here" into item 4 of Row
		put "Not Acknowledged" into Item 5 of row
		put "No Kibana Information" into Item 6 of Row
		put CRLF & row after file myfile
		Next Repeat
	End IF
	
	
	wait 4
	if imagefound(ImageName:"BlueTrack")
		rightclick convertedTrackCoord
		click "TTREPORTCLEAR"
		Typetext RightArrow, LeftArrow, RightArrow, ReturnKey
		Click (Image:"ReleaseDirection-NoDirection", WaitFor:23)
		Click (Image:"ReleaseDirection-Done", WaitFor:44)
		Typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnKey, REturnKey
		Typetext Returnkey, ReturnKey, REturnKey, returnKey, Returnkey, REturnKey, returnKey, Returnkey, ReturnKey, REturnKEy, REturnKey
		put myUID into Item 1 of row
		put myLocation into item 2 of Row
		put "No Authority Created" into item 3 of Row
		Put "Manually try to issue T&T here, Authority wasn't sent to the onboard" into item 4 of Row
		put "Not Acknowledged" into Item 5 of row
		put "No Kibana Information" into Item 6 of Row
		put CRLF & row after file myfile
		Next Repeat
	end if
	
	connect "SandSFRTATMC"
	if imagefound (ImageName: "AUTHORITYReview", Waitfor:30) then
		Click (Image:"AUTHORITYReview", WaitFor:180)
		Click (Image:"AuthorityAcknowledge", WaitFor:34)
		
		Click (Image:"AuthorityReturn", WaitFor:28)
		//Put myOldSysUID into item 1 of row
		//put myOldSignal && "@" && myOldEntryMP && myoldEntryCP && "to" && myoldExitSignal &&"@"&& myOldExitMP  && myOldExitCP into item 2 of Row
		//put myNum into item 3 of row
		//Put "Need Kibana acknowledge here" into item 4 of row
		//put "Future Kibana URL" into item 5 of row
		//put CRLF & row after file myfile
		connect "SandSFRVBO"
		wait 3
		Click (Image:"TMDS ICON", WaitFor:60)
		click "SYSTEMSUMMARY_1"
		wait 5
		click "AuthoritiesTab"
		
		if imagefound(ImageName:"AuthNum")then
			
			put imageLocation("AuthNum") into coord
			put coord + (0,30) into AuthNum
			click AuthNum
			put readtext(AuthNum) into myNum
			log myNum
		Else
			Log "screenLag"
		End if
		click "TMDS ICON"
		Click "TrainManagement"
		wait 1
		rightclick convertedTrackCoord
		click ("TTReportClear")
		Typetext RightArrow, LeftArrow, RightArrow, ReturnKey
		Click (Image:"ReleaseDirection-NoDirection", WaitFor:23)
		Click (Image:"ReleaseDirection-Done", WaitFor:44)
		Typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnKey, ReturnKey
		Typetext Returnkey, ReturnKey, REturnKey, returnKey, Returnkey, REturnKey, returnKey, Returnkey, REturnkEy, REturnKey, REturnKey
		
		connect "SandSFRTATMC"
		Click (Image:"AUTHORITYReview", WaitFor:180)
		Click (Image:"AuthorityAcknowledge", WaitFor:34)
		
		Wait 20
		connect "SandSFRVBO"
		click "TMDS ICON"
		Click "TrainManagement"
		rightclick convertedTrackCoord
		if imagefound(ImageName:"TTREPORTCLEAR")
			connect "SandSFRTATMC"
			Click (image: "Menu1", waitfor:60)
			click(image:"Cutout", waitfor:60)
			click(image: "CUTOUTENFORCEMENTYes", waitfor:60)
			Wait 10
			connect "SandSFRVBO"
			Click (Image:"TMDS ICON", WaitFor:60)
			wait 5
			Click "TrainManagement"	
			rightclick convertedTrackCoord
			click ("TTReportClear")
			Typetext RightArrow, LeftArrow, RightArrow, ReturnKey
			Click (Image:"ReleaseDirection-NoDirection", WaitFor:23)
			Click (Image:"ReleaseDirection-Done", WaitFor:44)
			Typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnKey, REturnKey
			Typetext Returnkey, ReturnKey, REturnKey, returnKey, Returnkey, REturnKey, returnKey, Returnkey, ReturnKey, REturnKey, ReturnKey
			wait 10
			Connect "SandSFRTATMC"
			click(image: "menu1", waitfor:300)
			click(image:"CutIn", waitfor:300)
			click (Image: "ACTIVATEENFORCEMENTYes", waitfor:300)
			click (image: "AcceptConsist", waitfor:300)
			click (image: "SELECTCURRENTTRACK", waitfor:300)
			
			click (image: "SelectTrack Yes",waitfor:300)
			click (image: "South", waitfor:300)
			click (image: "MainButton", waitfor:300)
			if imagefound(Image:"ACTIVE_1", WaitFor:120)
				connect "SandSFRVBO"
				Click (Image:"TMDS ICON", WaitFor:60)
				Click "TrainManagement"
				wait 2
				Click "YellowBannerTMDS"
				RightClick (Image:"ALERTTYPE", WaitFor:47)
				Click "ACKNOWLEDGEALL"
				Click "ACKNOWLEDGEALLALERTS"
				Click (Image:"TMDS ICON", WaitFor:60)
				Click "TrainManagement"
			Else
				wait 45
				connect "SandSFRVBO"
				Click (Image:"TMDS ICON", WaitFor:60)
				Click "TrainManagement"
				wait 2
				Click "YellowBannerTMDS"
				RightClick (Image:"ALERTTYPE", WaitFor:47)
				Click "ACKNOWLEDGEALL"
				Click "ACKNOWLEDGEALLALERTS"
				Click (Image:"TMDS ICON", WaitFor:60)
				Click "TrainManagement"
				
			end if
			put myUID into Item 1 of row
			put myLocation into item 2 of Row
			put myNum into item 3 of Row
			Put "CreatedT&T here, acknowledged voided T&T onboard but Authority left in CAD" into item 4 of Row
			put "Acknowledged" into Item 5 of row
			put "Future Kibana Information" into Item 6 of Row
			put CRLF & row after file myfile
		Else
			put myUID into Item 1 of row
			put myLocation into item 2 of Row
			put myNum into item 3 of Row
			Put "CreatedT&T here" into item 4 of Row
			put "Acknowledged" into Item 5 of row
			put "Future Kibana Information" into Item 6 of Row
			put CRLF & row after file myfile
		End IF
		Next Repeat
	End If
	
	
	if imageFound(ImageName: "SYNCHRONIZATIONERROR") then
		Click (Image:"SYNCHRONIZATIONERROR", waitfor:60)
		Click (image:"DegradedSystemAck", waitfor:60)
		Click (image: "Menu1", waitfor:60)
		click(image:"Cutout", waitfor:60)
		click(image: "CUTOUTENFORCEMENTYes", waitfor:60)
		Wait 10
		connect "SandSFRVBO"
		Click (Image:"TMDS ICON", WaitFor:60)
		click "SYSTEMSUMMARY_1"
		wait 5
		click "AuthoritiesTab"
		
		if imagefound(ImageName:"AuthNum")then
			
			put imageLocation("AuthNum") into coord
			put coord + (0,30) into AuthNum
			click AuthNum
			put readtext(AuthNum) into myNum
			log myNum
		Else
			Log "screenLag"
		End if
		Click (Image:"TMDS ICON", WaitFor:60)
		Click "TrainManagement"	
		rightclick convertedTrackCoord
		click ("TTReportClear")
		Typetext RightArrow, LeftArrow, RightArrow, ReturnKey
		Click (Image:"ReleaseDirection-NoDirection", WaitFor:23)
		Click (Image:"ReleaseDirection-Done", WaitFor:44)
		Typetext downArrow, uparrow, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, ReturnKey, REturnKey, REturnKey, REturnKey
		Typetext Returnkey, ReturnKey, REturnKey, returnKey, Returnkey, REturnKey, returnKey, Returnkey, ReturnKey, ReturnKey, REturnKey
		wait 10
		//Put myOldSysUID into item 1 of row
		//put myOldSignal && "@" && myOldEntryMP && myoldEntryCP && "to" && myoldExitSignal &&"@"&& myOldExitMP  && myOldExitCP into item 2 of Row
		//Put "Authority created but onboard went out of sync" into item 3 of row
		//put "Not Acknowledged" into Item 4 of row
		//put "No Kibana Information" into Item 5 of Row
		//put CRLF & row after file myfile
		
		Connect "SandSFRTATMC"
		click(image: "menu1", waitfor:300)
		click(image:"CutIn", waitfor:300)
		click (Image: "ACTIVATEENFORCEMENTYes", waitfor:300)
		click (image: "AcceptConsist", waitfor:300)
		click (image: "SELECTCURRENTTRACK", waitfor:300)
		
		click (image: "SelectTrack Yes",waitfor:300)
		click (image: "South", waitfor:300)
		click (image: "MainButton", waitfor:300)
		if imagefound(Image:"ACTIVE_1", WaitFor:120)
			connect "SandSFRVBO"
			Click (Image:"TMDS ICON", WaitFor:60)
			Click "TrainManagement"
			wait 2
			Click "YellowBannerTMDS"
			RightClick (Image:"ALERTTYPE", WaitFor:47)
			Click "ACKNOWLEDGEALL"
			Click "ACKNOWLEDGEALLALERTS"
			Click (Image:"TMDS ICON", WaitFor:60)
			Click "TrainManagement"
		Else
			wait 45
			connect "SandSFRVBO"
			Click (Image:"TMDS ICON", WaitFor:60)
			Click "TrainManagement"
			wait 2
			Click "YellowBannerTMDS"
			RightClick (Image:"ALERTTYPE", WaitFor:47)
			Click "ACKNOWLEDGEALL"
			Click "ACKNOWLEDGEALLALERTS"
			Click (Image:"TMDS ICON", WaitFor:60)
			Click "TrainManagement"
		end if
		put myUID into Item 1 of row
		put myLocation into item 2 of Row
		put myNum into item 3 of Row
		Put "Onboard Went out of sync" into item 4 of Row
		put "Not Acknowledged" into Item 5 of row
		put "No Kibana Information" into Item 6 of Row
		put CRLF & row after file myfile
		Next Repeat
	End IF
	
End Repeat